services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: always

  web-dev:
    image: node:24
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
